FROM node:latest as build

WORKDIR /frontend

COPY package*.json ./

ENV PATH /app/node_modules/.bin:$PATH

RUN npm ci 
COPY . .
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
RUN npm run build
FROM nginx:latest
COPY --from=build /frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /frontend/build /usr/share/nginx/html