services:
  backend:
    build: ./backend
    command: npm run start:dev
    working_dir: /backend
    volumes:
      - ./backend:/backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 8000:8000
    restart: on-failure
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
      - frontend
