services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    working_dir: /backend
    ports:
      - 8000:8000
    restart: on-failure
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_BACKEND_URL=http://wbtestdomain.ru/api
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    restart: always
