name: CI

on:
  push:
    branches: [main]

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run backend linter
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --exit-code-from lint_backend lint_backend
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run backend tests
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --exit-code-from test_backend test_backend
  frontend-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run frontend tests
          run: |
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --exit-code-from test_frontend test_frontend
  frontend-lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run frontend linter
          run: |
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --exit-code-from lint_frontend lint_frontend